lowRISC/manticore

.crates-io-staging/Cargo.toml, .crates-io-staging/README.md, .crates-io-staging/README.md.crates-io, .crates-io-staging/src/lib.rs, Cargo.toml
crates.io has a first-come-first-serve name policy, and a no-deletions policy (in other words, they will *not* honor our use of the name if someone scoops us). Thus, while Manticore is not suitable to publish yet, we do need to hold onto the name for now.
=> [cargo] Add a temporary project to hold `mantiocore` on crates.io

.github/workflows/rust.yml, Cargo.toml, src/crypto/mod.rs, src/crypto/ring/mod.rs, src/crypto/ring/rsa.rs, src/crypto/ring/sha256.rs, src/lib.rs, src/manifest/mod.rs, src/server/pa_rot.rs
This PR also moves around some Cargo features. In particular, `std` and `ring` are both included by default, because they are necessary for tests (Cargo does not allow specifying additional test-only features, and this behavior seems consistent with other crates).
=> [ring] Make crypto::ring part of Manticore's API

src/io/cursor.rs, src/manifest/container.rs, src/manifest/fpm.rs, src/manifest/mod.rs
This change adds the necessary functions for actually *making* signed manifests, given a signing key and an in-Rust representation of a manifest we want to sign.
In a followup, I'll add serde support for the FPM, and thread all that together on Oskar's tool.
=> [manifest] Add `Containerizer`, a manifest builder.

src/lib.rs, src/net.rs, src/server/handler.rs, src/server/pa_rot.rs
This change adds a module that abstracts over a "network connection", via the `HostPort` trait. This trait is intended to replace the current ad-hoc `manticore::protocol::Header` wire format, and to implement transport-agnosticism in Manticore.
Still pending: integration into `manticore::server::handler::Handler`. I'd like to get this design triple-checked before I go and do the work to plug it in everywhere.
=> [net] Introduce transport-layer agnosticism

Cargo.toml, src/main.rs, src/protocol/wire.rs
This change simplifies some of the code in manticore-tool, to make it easier to add more commands in the future.
This probably aught to have been broken up into multiple commits but it wound up being more work than was worth it. =/
=> [tool] Clean up manticore-tool

src/hardware/flash.rs, src/hardware/mod.rs, src/main.rs, src/manifest/container.rs, src/manifest/fpm.rs, src/manifest/mod.rs
This change lays the groundwork for doing "non-buffering" manifest operations, and, eventually, manifest activation.
Manifests are expected to live off-device, and expecting to be able to buffer all of a manifest at any given time is too stringent of a requirement. In a followup, we will expand this support to the FPM.
=> Move `manifest::Container` to a new, buffer-free API

src/hardware/flash.rs, src/main.rs, src/manifest/container.rs, src/manifest/fpm.rs, src/mem/arena.rs, src/mem/mod.rs, src/protocol/device_info.rs, src/protocol/firmware_version.rs
This PR is the result of a lot of pain and suffering on my part trying to make the existing Arena and Flash APIs do the right thing for parsing the PFM. I discovered a few things:
- Coupling the lifetimes of allocations in RAM and a Flash object too closely results in some very difficult to resolve lifetime constraints.
- There's no good way for parsing "packed C structs" out of Flash, which is something Cerberus, as a protocol, expects implementors to do.
- The adapters in flash.rs were mostly unhelpful in this regard, since you really want to bind a Flash to a lifetime by using `&'flash Flash`.
- Region/Ptr feel too boilerplatey and hard to use.
The result is this PR, which contains a number of interrelated changes to how Arenas and Flashes interact. The most important once is the …
=> [flash/mem] Significant changes to how Manticore does memory management

src/hardware/flash.rs, src/main.rs, src/manifest/mod.rs, src/manifest/pfm.rs
This is the first change that adds basic PFM support: parsing a PFM's TOC, and extracting the simples of the PFM elements (the Platform ID). It also includes a simple test that makes sure the simplest case works.
=> [manifest] Add PFM support (for real this time!)

src/manifest/mod.rs, src/manifest/pfm.rs, src/mem/mod.rs
This change makes it possible to parse the "meat" of the PFM: namely, the parts which describe the memory layout of a flash firmware image.
~~This PR builds but is currently untested. Tests will be following along soon.~~
The PR as implemented is slightly incompatible with Microsoft's latest format proposal. A followup PR will:
- Delete the FPM (since we don't need it anymore).
- Move the TOC stuff to the "container" library (since it's intended to be a general Manifest format).
- Bring us up to compatibility with the current proposal.
=> [manifest] Add more PFM manipulation functions

src/net.rs, src/protocol/mod.rs, src/server/handler.rs, src/server/pa_rot.rs
This is a WIP attempt at adding a `DevicePort` implementation to Manticore.
This implementation varies greatly from the current `HostPort` implementation, which is why I'm sending a draft PR to see what others think.
The current `HostPort` implementation seems a little complex and I don't think it will integrate well into libtock-rs and the Tock runtime. For example the `HostPort` `receive`() function is blocking, while libtock-rs is non-blocking.
The `DevicePort` implementation is more geared towards integration with libtock-rs and the Tock ecosystem. I wanted to get feedback on the idea before I spend too much time writing documentation, tests and functionality.
=> net: Add a DevicePort implementation

src/hardware/flash.rs, src/manifest/container.rs, src/manifest/mod.rs, src/manifest/owned/mod.rs, src/manifest/owned/pfm.rs, src/manifest/pfm.rs
Unfortunately, this does not include `thiserror` support, because that crate requires `std`.
=> [manifest] Improve the quality of errors emitted by the `manifest` module.

src/manifest/container.rs, src/manifest/mod.rs, src/manifest/owned/mod.rs, src/manifest/owned/pfm.rs, src/manifest/pfm.rs
This change has two benefits:
- It removes proliferation of repeated type parameters all over the place,
since we can now write `Pfm` instead of `ParsedPfm<'all, 'kinds, Of,
Stuff>`.
- It makes it possible to have code generic over all Pfms that can
specialize a ParsedPfm for different Flash types and whatnot with
minimal threading of type parameters around.
This will be particularly useful when we add the manifest manager, which needs to be able to deal with manifests of fixed type but different underlying storage.
=> [manifest] Add an intermediate type to represent all PFMs as a whole

src/hardware/mod.rs, src/server/pa_rot.rs
Extend the `Identity` trait with a new `vendor_firmware_version()`
to support `FirmwareVersionRequest` requests with `index != 0`.
=> Add support for vendor_firmware_version.

src/cert/x509.rs, src/cert/x509_test.rs, src/crypto/ring/rsa.rs, src/crypto/sig.rs, src/manifest/container.rs, src/manifest/owned/mod.rs
This is mostly to enable zero-copy signing for things like CBOR and some
of the Cerberus challenge messages, which compute signatures over
disjoint buffers.
=> [crypto] Make the signature APIs use iovec inputs

.github/workflows/rust.yml, Cargo.toml, e2e/Cargo.toml, e2e/README.md, e2e/src/main.rs, e2e/src/pa_rot.rs, e2e/src/tcp.rs
`manticore-e2e` spawns a child processes to use as a "virtual RoT", speaking Cerberus over TCP. I intend to begin growing a proper conformance suite around this virtual RoT. This has three benefits:
1. e2e test for manticore itself are great.
2. We can eventually use this to test Azure's implementation as well.
3. This is intended to (eventually) be an example integration for interested Manticore users.
TODO: Add doc comments to everything.
=> Add the beginnings of proper end-to-end testing for Manticore

.github/workflows/rust.yml, src/cert/cwt/test.rs, src/cert/x509/test.rs, src/crypto/ring/rsa.rs, src/crypto/ring/sha256.rs, src/manifest/container.rs, src/manifest/owned/pfm.rs, src/manifest/pfm.rs
A handful of tests are currently disabled in Miri mode because they need to call into `ring`'s copy of BoringSSL.
=> [ci] Run as many unit tests as possible on Miri

.github/workflows/rust.yml
This should stop format/clippy errors from blocking the build
altogether.
=> [ci] Break off linting into its own job

.github/workflows/rust.yml
Modifying the CI configs apparently has hardly any guardrails. I have yet to find how to make it impossible to merge changes to configuration with syntax errors.
=> [ci] Fix a syntax error in CI config

.github/workflows/rust.yml, e2e/Cargo.toml, e2e/README.md, e2e/run.sh, e2e/src/main.rs, e2e/src/pa_rot.rs, e2e/src/tcp.rs, e2e/src/tests/device_queries.rs
Different approach to #92, which avoids having to reinvent a test harness ourselves.
=> [e2e] Make it possible to use Rust's test harness for e2e tests

fuzz/targets/x509_unsigned.rs, src/crypto/ring/rsa.rs, src/crypto/ring/sha256.rs, src/crypto/ring/sig.rs, src/crypto/rsa.rs, src/crypto/sha256.rs, src/crypto/sig.rs, src/manifest/mod.rs, src/manifest/owned/mod.rs
Originally, there was a desire for custom implementations to be able to
spit out errors about their internals. In practice, this isn't a great
idea for two reasons:
- Unnecessary complexity due to extra type parameters.
- Leaking internal state of engines isn't very useful (or secure!).
Engine-specific errors will probably want to be logged via an
integration-specific side-channel.
=> [crypto] Remove unnecessarilly-generic errors

fuzz/targets/x509_unsigned.rs
GitHub does not run pre-merge checks when rebasing, and two changes to
CI raced each other and broke.
=> [fuzz] Fix broken CI again

src/io/cursor.rs, src/protocol/capabilities.rs, src/protocol/challenge.rs, src/protocol/device_id.rs, src/protocol/device_info.rs, src/protocol/device_uptime.rs, src/protocol/firmware_version.rs, src/protocol/get_cert.rs, src/protocol/get_digests.rs, src/protocol/macros.rs, src/protocol/mod.rs, src/protocol/request_counter.rs, src/protocol/reset_counter.rs, src/protocol/wire.rs, src/server/handler.rs
The distinction is essentially unnecessary, since ToWire was a subset of FromWire. Moreover, the OutOfRange error is potentially useful for ToWire in some cases.
=>  [protocol] Merge `(From|To)WireError` into one

src/mem/arena.rs, src/protocol/macros.rs
This rearranges the `unsafe` inside of `BumpArena` somewhat, but I've written comments describing why this is OK.
=> [mem] Allow inline arrays for BumpArena storage

src/protocol/get_host_state.rs
The failure is inside of a `protocol` macro, which is likely because I merged a contributor's PR in a bad way that CI failed to catch. See:
```rust
error: expected identifier
--> src/protocol/macros.rs:89:13
|
89 |               $field_vis $field: $field_ty,
|               ^^^^^^^^^^
| 
::: src/protocol/get_host_state.rs:63:1
|
63 | / make_fuzz_safe! {
64 | |     /// The [`GetHostState`] response.
65 | |     #[derive(Clone, Copy, PartialEq, Eq, Debug)]
66 | | #[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
...  |
69 | |     }
70 | | }
| |_- in this macro invocation
```
GH's presubmits seem to be more of a suggestion than a hard guardrail sometimes...
=> [protocol] Fix a build error in some configurations

.github/workflows/fuzz.yml, fuzz/Cargo.toml, fuzz/gen/manticore_protocol_key_exchange_KeyExchange__req_from_wire.rs, fuzz/gen/manticore_protocol_key_exchange_KeyExchange__req_to_wire.rs, fuzz/gen/manticore_protocol_key_exchange_KeyExchange__resp_from_wire.rs, fuzz/gen/manticore_protocol_key_exchange_KeyExchange__resp_to_wire.rs, fuzz/proto_types.txt, src/io/read.rs, src/protocol/key_exchange.rs, src/protocol/macros.rs, src/protocol/mod.rs
Note that fuzz tests are missing; this is blocked on #115.
=> [protocol] Add parsers for the KeyExchange messages

e2e/Cargo.toml, e2e/run.sh, e2e/src/main.rs, e2e/src/pa_rot.rs
This makes logs captures from a subprocess be treated as "test output" so the Rust test harness can filter it appropriately.
We achieve this by spawning a thread to forward stderr manually.
We also set up logging in the test harness itself.
=> [e2e] Improve debugging output

Cargo.toml, src/hardware/flash.rs, src/io/read.rs, src/mem/arena.rs
=> [meta] Add dependency on `extend` to cut down boilerplate

Cargo.toml, src/cert/chain.rs, src/crypto/csrng.rs, src/crypto/sig.rs, src/hardware/flash.rs, src/hardware/mod.rs, src/io/read.rs, src/io/write.rs, src/mem/arena.rs, src/net.rs
To test for object safety, we simply need to utter the type `dyn Trait`; if the trait is not object-safe, its `dyn` cannot be uttered.
This is what the macro we were using was basically already doing, but this lets us drop a dependency.
=> [meta] Use `impl dyn Trait` as the object-safety assert idiom

e2e/src/pa_rot.rs, src/lib.rs, src/server/pa_rot.rs, src/session/mod.rs, src/session/ring.rs
Also includes part of an implementation of session estabilishment in the PA-RoT server.
The implementation is incomplete; I need to re-write the SHA-2/HMAC interfaces first.
=> [session] Create an interface for managing session keys

src/protocol/capabilities.rs, src/protocol/challenge.rs, src/protocol/device_id.rs, src/protocol/device_info.rs, src/protocol/device_uptime.rs, src/protocol/error.rs, src/protocol/firmware_version.rs, src/protocol/get_cert.rs, src/protocol/get_digests.rs, src/protocol/get_host_state.rs, src/protocol/key_exchange.rs, src/protocol/mod.rs, src/protocol/request_counter.rs, src/protocol/reset_counter.rs, src/server/handler.rs, src/server/pa_rot.rs
What it says in the title: handlers now use proper errors instead of hand-rolling Cerberus errors.
Right now all the Manticore-specific errors use the "vendor specified" error format, but hopefully this PR can be used as a model for better error handling in Cerberus in the future.
=> [protocol] Add a richer API for declaring message-specific errors

e2e/src/pa_rot.rs, e2e/src/tcp.rs, e2e/src/tests/challenge.rs, e2e/src/tests/device_queries.rs, src/crypto/hash.rs, src/protocol/capabilities.rs, src/protocol/challenge.rs, src/protocol/device_id.rs, src/protocol/error.rs, src/protocol/template.rs, src/protocol/wire.rs, src/server/handler.rs, src/server/pa_rot.rs
This change is similar in spirit to 82ef871a, which trades off using a
dyn for cutting down on type parameters. Similar reasoning applies here;
in practice, calling into an arena is quite rare, and we were already
forced into dyn Arenas to make other, more complex traits be
object-safe, too.
=> [mem] Switch all uses of Arena to be trait objects

e2e/src/pa_rot.rs, e2e/src/tcp.rs, src/net/device.rs, src/net/host.rs, src/net/mod.rs, src/server/handler.rs, src/server/pa_rot.rs
This change makes HostPort and the handler framework built on top of it
parametric over the Header type; there is now a net::CerberusHeader
specifically for Cerberus, which will be followed up with a
net::SpdmHeader, allowing us to reuse most of Manticore's infrastructure
for implementing SPDM.
Note: this PR is based on #137; only the lastest commit is relevant.
=> [server] Parametrize the handler framework over header types

e2e/src/pa_rot.rs, e2e/src/tcp.rs, src/net/mod.rs, src/protocol/cerberus/challenge.rs, src/protocol/cerberus/get_cert.rs, src/protocol/cerberus/get_digests.rs, src/protocol/cerberus/key_exchange.rs, src/protocol/error.rs, src/protocol/mod.rs, src/protocol/template.rs, src/server/handler.rs, src/server/pa_rot.rs, tool/src/message.rs
Changes include:
- Merger of `Request` and `Response` into `Message`.
- New `Command::CommandType` associated type to simplify several `where` clauses.
- Move `ReqOf`, `RespOf`, and `ErrOf` into `protocol`'s public API.
- Use all of the above to simplify message-manipulation code.
=> [protocol] Clean up and reorganize the `manticore::protocol` traits.

Cargo.toml, e2e/src/pa_rot.rs, src/crypto/ring/sig.rs, src/manifest/mod.rs, src/protocol/cerberus/capabilities.rs, src/protocol/mod.rs, src/protocol/spdm/get_caps.rs, src/protocol/template.rs, src/protocol/wire.rs, src/serde.rs, src/server/pa_rot.rs
I'm a bit concerned with how fuzzing is grafted into this; it may be prudent to upgrade our libfuzzer, or try to get a patch into arbitrary-derive that adds a way of intercepting an Arbitrary definition into one of the fields...
=> [protocol] Start switching to `enumflags2`

Cargo.toml, cerberus-tables/Cargo.toml, cerberus-tables/README.md, cerberus-tables/src/ast/fmt.rs, cerberus-tables/src/ast/mod.rs, cerberus-tables/src/ast/parser.rs, cerberus-tables/src/main.rs
There is a [recently merged RFC](https://github.com/opencomputeproject/Security/blob/master/RoT/Protocol/RFCs/0003-Command_Definition_Syntax.md) in Cerberus that adds tables to the effect of
`message AttestationLogFormat`
| Type     | Name                | Description                                 |
|----------|---------------------|---------------------------------------------|
| `0x0b`   | `header_format`     | Header format version.                      |
| `b16`    | `entry_length`      | Total length of the entry.                  |
| `b32`    | `unique_id`         | A unique identifier for the entry.          |
| `b32`    | `tcg_type`          | The associated TCG event type.              |
| `b8`     | `measurement_index` | Index of the measurement within the PMR.    |
| `b8` …
=> [tables] Add a parser for the Cerberus Message Table format
